FROM node:20

WORKDIR /app

COPY package*.json /app/

# RUN npm install
RUN npm install --retry=5 --retry-delay=2000 --timeout=300000

RUN npx -y playwright install --with-deps

COPY ./ /app/

ARG VITE_API_URL=${VITE_API_URL}
