"""Initial migration with all models including conversationmessage role column

Revision ID: 530d1a0e2cc7
Revises: 
Create Date: 2025-10-26 06:58:28.337302

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '530d1a0e2cc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversationmessage', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.add_column('conversationmessage', sa.Column('images', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=True))
    op.drop_column('conversationmessage', 'sender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversationmessage', sa.Column('sender', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('conversationmessage', 'images')
    op.drop_column('conversationmessage', 'role')
    # ### end Alembic commands ###
